name: "release"

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'Python/main.spec'
          requirements: 'Python/requirements.txt'
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: '../heartrate-release.zip'
          directory: ./dist
      - name: tree
        run: |
          tree
          dir
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: 'heartrate-release.zip'
          draft: true
          body: "Automated release."
          fail_on_unmatched_files: true